# SEE https://github.com/E85Addict/revanced-extended-builds/blob/main/CONFIG.md for more detailed explanations

[main-config]
compression-level = 9         # compression level for module zips. between 1 and 9
enable-magisk-update = true   # set this to false if you do not want to receive updates from magisk app
parallel-jobs = 6             # max number of concurrent building jobs
update-prebuilts = true       # dont touch this
build-mindetach-module = true


[YouTube-Revancify]
enabled = true                                                        # add 'enabled = false' key to entries to not build them
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "debugging custom-branding-icon-afn-red custom-branding-name"# whitespace seperated list of patches to exclude
included-patches = "custom-branding-icon-revancify"             # whitespace seperated list of patches to include
version = "auto"                                                      # 'auto', 'latest' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
merge-integrations = true
rip-libs = true

[YouTube-Red]
enabled = true 
build-mode = "both"
excluded-patches = "debugging custom-branding-icon-revancify custom-branding-name"
included-patches = "custom-branding-icon-afn-red"
version = "auto"
exclusive-patches = false
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvr-magisk"
merge-integrations = true
rip-libs = true

[YouTube-Blue]
enabled = true
build-mode = "both"
excluded-patches = "debugging custom-branding-icon-afn-red  custom-branding-icon-revancify custom-branding-name"
included-patches = "custom-branding-icon-afn-blue"
version = "auto"  
exclusive-patches = false
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvb-magisk"
merge-integrations = true
rip-libs = true

[Music-arm64-Revancify]
enabled = true
build-mode = "both"
app-name = "Music"
excluded-patches = "custom-branding-music-red custom-branding-music-blue"
included-patches = "custom-branding-music-revancify"
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrv-magisk"
arch = "arm64-v8a"
merge-integrations = true

[Music-arm64-Red]
enabled = true
build-mode = "both"
app-name = "Music"
excluded-patches = "custom-branding-music-blue custom-branding-music-revancify"
included-patches = "custom-branding-music-red"
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvr-magisk"
arch = "arm64-v8a"
merge-integrations = true

[Music-arm64-Blue]
enabled = true
build-mode = "both"
app-name = "Music"
excluded-patches = "custom-branding-music-red custom-branding-music-revancify"
included-patches = "custom-branding-music-blue"
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvb-magisk"
arch = "arm64-v8a"
merge-integrations = true

[Music-arm-Revancify]
enabled = false
build-mode = "both"
app-name = "Music"
excluded-patches = "custom-branding-music-red custom-branding-music-blue"
included-patches = "custom-branding-music-revancify"
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrv-arm-magisk"
arch = "arm-v7a"
merge-integrations = true

[Music-arm-Red]
enabled = false
build-mode = "both"
app-name = "Music"
excluded-patches = "custom-branding-music-blue custom-branding-music-revancify"
included-patches = "custom-branding-music-red"
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvr-arm-magisk"
arch = "arm-v7a"
merge-integrations = true

[Music-arm-Blue]
enabled = false
build-mode = "both"
app-name = "Music"
excluded-patches = "custom-branding-music-red custom-branding-music-revancify"
included-patches = "custom-branding-music-blue"
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvb-arm-magisk"
arch = "arm-v7a"
merge-integrations = true